apiVersion: apps/v1
kind: Deployment
metadata:
  name: geetha-micro
  labels:
    app: geetha-micro
  namespace: geetha  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geetha-micro
  template:
    metadata:
      labels:
        app: geetha-micro
    spec:
      containers:
        - name: geetha-micro
          image: raman123/raman-customer-orders-services2:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "250m"
              memory: "250Mi"
