apiVersion: apps/v1
kind: Deployment
metadata:
  name: geetha-micro
  labels:
    app: geetha-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geetha-micro
  template:
    metadata:
      labels:
        app: geetha-micro
    spec:
      containers:
        - name: geetha-micro
          image: docker.io/raman/raman-micro:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
